const loginOtpEmail = (data) => {
    return `<!doctype html><html lang='en-US'><head><meta content='text/html; charset=utf-8' http-equiv='Content-Type'/><meta name='description' content='Reset Password.'><style type='text/css'>a:hover{text-decoration:underline!important;}</style></head><body marginheight='0' topmargin='0' marginwidth='0' leftmargin='0' style='margin:0;background-color:#f2f3f8;'><table cellspacing='0' border='0' cellpadding='0' width='100%' bgcolor='#f2f3f8'><tr><td><table style='background-color:#f2f3f8;max-width:670px;margin:0 auto;' width='100%' border='0' align='center' cellpadding='0' cellspacing='0'><tr><td style='height:35px;'>&nbsp;</td></tr><tr><td style='text-align:center;'></td></tr><tr><td style='height:20px;'>&nbsp;</td></tr><tr><td><table width='95%' border='0' align='center' cellpadding='0' cellspacing='0' style='max-width:670px;background:#fff;border-radius:3px;text-align:center;-webkit-box-shadow:0 6px 18px 0 rgba(0,0,0,.06);-moz-box-shadow:0 6px 18px 0 rgba(0,0,0,.06);box-shadow:0 6px 18px 0 rgba(0,0,0,.06);'><tr><td style='height:40px;'>&nbsp;</td></tr><tr><td style='padding:0 35px 30px 35px;'><img src='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQG4lo39vSLS1FaLIpr1XKrjiebmWX-3fRErA&s' width='200px' style='margin-bottom:20px;'/><h1 style='color:#1e1e2d;font-weight:500;margin:0;font-size:25px;font-family:Rubik,sans-serif;'></h1><span style='display:inline-block;vertical-align:middle;margin:29px 0 26px;border-bottom:1px solid #cecece;width:100px;'></span><p style='color:#455056;font-size:15px;margin:0;text-align:left!important;'>Dear ${data.firstName},<br/>We received a sign-in request for your account on the Bajaj API Developer Portal.</p><br><p style='color:#455056;font-size:15px;margin:0;text-align:left!important;'>To verify your credentials and complete the login, please use the One-Time Password (OTP) below:<br><b>${data.otp}</b></p><br><p style='color:#455056;font-size:15px;margin:0;text-align:left!important;'>Thanks & Regards,<br>Mulesoft Support<br>Digital & Analytics | Bajaj Auto Limited</p><p style='color:#ffffff;font-size:15px;text-align:left;background:linear-gradient(180deg,#0087FF 0%,#0052A4 100%);padding:20px;'>For any Production issue, please send an email to: <a href='' style='color:white;'>apigwsupport@bajajauto.co.in</a></p></td></tr></table></td></tr></table></td></tr></table></body></html>`
}
const signUpOtpEmail = (data) => {
    return `<!doctype html><html lang='en-US'><head><meta content='text/html; charset=utf-8' http-equiv='Content-Type'/><meta name='description' content='Reset Password.'><style type='text/css'>a:hover{text-decoration:underline!important;}</style></head><body marginheight='0' topmargin='0' marginwidth='0' leftmargin='0' style='margin:0;background-color:#f2f3f8;'><table cellspacing='0' border='0' cellpadding='0' width='100%' bgcolor='#f2f3f8'><tr><td><table style='background-color:#f2f3f8;max-width:670px;margin:0 auto;' width='100%' border='0' align='center' cellpadding='0' cellspacing='0'><tr><td style='height:35px;'>&nbsp;</td></tr><tr><td style='text-align:center;'></td></tr><tr><td style='height:20px;'>&nbsp;</td></tr><tr><td><table width='95%' border='0' align='center' cellpadding='0' cellspacing='0' style='max-width:670px;background:#fff;border-radius:3px;text-align:center;-webkit-box-shadow:0 6px 18px 0 rgba(0,0,0,.06);-moz-box-shadow:0 6px 18px 0 rgba(0,0,0,.06);box-shadow:0 6px 18px 0 rgba(0,0,0,.06);'><tr><td style='height:40px;'>&nbsp;</td></tr><tr><td style='padding:0 35px 30px 35px;'><img src='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQG4lo39vSLS1FaLIpr1XKrjiebmWX-3fRErA&s' width='200px' style='margin-bottom:20px;'/><h1 style='color:#1e1e2d;font-weight:500;margin:0;font-size:25px;font-family:Rubik,sans-serif;'></h1><span style='display:inline-block;vertical-align:middle;margin:29px 0 26px;border-bottom:1px solid #cecece;width:100px;'></span><p style='color:#455056;font-size:15px;margin:0;text-align:left!important;'>Dear ${data.firstName},<br/><br/>Thank you for registering on the Bajaj API Developer Portal.</p><br><p style='color:#455056;font-size:15px;margin:0;text-align:left!important;'>To verify your email address and activate your account, please use the One-Time Password (OTP) below<br><b>${data.otp}</b></p><br><p style='color:#455056;font-size:15px;margin:0;text-align:left!important;'>Thanks & Regards,<br>Mulesoft Support<br>Digital & Analytics | Bajaj Auto Limited</p><p style='color:#ffffff;font-size:15px;text-align:left;background:linear-gradient(180deg,#0087FF 0%,#0052A4 100%);padding:20px;'>For any Production issue, please send an email to: <a href='' style='color:white;'>apigwsupport@bajajauto.co.in</a></p></td></tr></table></td></tr></table></td></tr></table></body></html>`
}

export {
    loginOtpEmail,
    signUpOtpEmail
}